run:
  timeout: 5m
  tests: false
  allow-parallel-runners: true
  go: '1.20'
  concurrency: 4

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
  show-stats: true

linters:
    disable-all: true
    enable:
      - gosimple
      - govet
      - staticcheck
      - unused
      - gofmt
      - gosec
      - stylecheck
      - revive