version: 2
project_name: bbrew

builds:
  - id: bbrew
    main: ./cmd/bbrew
    binary: bbrew
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'bbrew/internal/services.AppVersion={{ .Version }}'

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: Valkyrie00
    name: bold-brew
  draft: false
  prerelease: auto
  header: |
    ## Bold Brew {{ .Version }}
    
    Install or upgrade:
    ```bash
    brew upgrade bbrew
    # or
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Valkyrie00/bold-brew/main/install.sh)"
    ```

brews:
  - name: bbrew
    homepage: "https://bold-brew.com"
    description: "Modern TUI for managing Homebrew packages and casks on macOS and Linux"
    license: "MIT"
    url_template: "https://github.com/Valkyrie00/bold-brew/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    test: |
      assert_match "Usage", shell_output("#{bin}/bbrew -h")
    install: |
      bin.install "bbrew"
    repository:
      owner: Valkyrie00
      name: homebrew-bbrew
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "⚠️ Breaking Changes"
      regexp: "^.*!:.+$"
      order: 0
    - title: "✨ Features"
      regexp: "^.*feat[(\\w)]*:.*$"
      order: 1
    - title: "🐛 Bug Fixes"
      regexp: "^.*fix[(\\w)]*:.*$"
      order: 2
    - title: "♻️ Refactoring"
      regexp: "^.*refactor[(\\w)]*:.*$"
      order: 3
    - title: "⚡️ Performance"
      regexp: "^.*perf[(\\w)]*:.*$"
      order: 4
    - title: "🔒 Security"
      regexp: "^.*security[(\\w)]*:.*$"
      order: 5