version: 2
project_name: bbrew
builds:
  - id: bbrew
    main: ./cmd/bbrew
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'bbrew/internal/services.AppVersion={{ .Version }}'
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
brews:
  - name: bbrew
    homepage: "https://github.com/Valkyrie00/bold-brew"
    description: "A simple TUI tool to make your homebrew bold."
    url_template: "https://github.com/Valkyrie00/bold-brew/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    test: |
      system "#{bin}/bbrew --version"
    install: |
      bin.install "bbrew"
    repository:
      owner: Valkyrie00
      name: homebrew-bbrew
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: '⚠️ Breaking Changes'
      regexp: "^.*!:.+$"
      order: 0
    - title: '✨ Features'
      regexp: "^.*feat[(\\w)]*:.*$"
      order: 1
    - title: '🐛 Bug Fixes'
      regexp: "^.*fix[(\\w)]*:.*$"
      order: 2
    - title: '⚡️ Improvements'
      regexp: "^.*perf[(\\w)]*:.*$"
      order: 3