package services

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"bbrew/internal/models"
)

// ExportBrewfile generates a Brewfile from the currently installed packages.
// Returns the file path where the Brewfile was written.
func (s *AppService) ExportBrewfile() (string, error) {
	s.mu.RLock()
	packages := s.packages
	s.mu.RUnlock()

	if packages == nil || len(*packages) == 0 {
		return "", fmt.Errorf("no packages loaded")
	}

	var taps []string
	var formulae []string
	var casks []string

	tapSet := make(map[string]bool)

	for _, pkg := range *packages {
		if !pkg.LocallyInstalled {
			continue
		}

		switch pkg.Type {
		case models.PackageTypeCask:
			casks = append(casks, pkg.Name)
		case models.PackageTypeFormula:
			formulae = append(formulae, pkg.Name)
			if pkg.Formula != nil && strings.Contains(pkg.Formula.FullName, "/") {
				parts := strings.SplitN(pkg.Formula.FullName, "/", 3)
				if len(parts) >= 3 {
					tap := parts[0] + "/" + parts[1]
					if !tapSet[tap] {
						tapSet[tap] = true
						taps = append(taps, tap)
					}
				}
			}
		default:
			continue
		}
	}

	sort.Strings(taps)
	sort.Strings(formulae)
	sort.Strings(casks)

	var sb strings.Builder
	fmt.Fprintf(&sb, "# Generated by Bold Brew on %s\n\n", time.Now().Format("2006-01-02"))

	if len(taps) > 0 {
		for _, tap := range taps {
			fmt.Fprintf(&sb, "tap \"%s\"\n", tap)
		}
		sb.WriteString("\n")
	}

	if len(formulae) > 0 {
		for _, f := range formulae {
			fmt.Fprintf(&sb, "brew \"%s\"\n", f)
		}
		sb.WriteString("\n")
	}

	if len(casks) > 0 {
		for _, c := range casks {
			fmt.Fprintf(&sb, "cask \"%s\"\n", c)
		}
	}

	home, err := os.UserHomeDir()
	if err != nil {
		home = "."
	}
	outputPath := filepath.Join(home, "Brewfile")

	if err := os.WriteFile(outputPath, []byte(sb.String()), 0600); err != nil {
		return "", fmt.Errorf("failed to write Brewfile: %w", err)
	}

	return outputPath, nil
}
